#!/bin/sh
cd `dirname $0`
export LD_LIBRARY_PATH="./lib"
if [ -n "$JAVA_HOME" ]; then
  $JAVA_HOME/bin/java -client Xmx256m -Dsun.java2d.opengl=true -jar ./Alchemy.jar $*
else
  java -client -Xmx256m -Dsun.java2d.opengl=true -jar ./Alchemy.jar $*
fi
cd $OLDPWD